/*
 * The bitmap fonts of the device UI (TSK-S4-10).
 *
 * Generated by scripts/gen_ui_fonts.sh from Be Vietnam Pro (OFL-1.1, see
 * LICENSES/OFL-1.1.txt and NOTICE) with lv_font_conv, over the ranges in
 * fonts/ranges.txt. Do not edit the .c files by hand: regenerate with
 *
 *     bash scripts/gen_ui_fonts.sh
 *
 * and read docs/spec/ui.md §Phông chữ when changing sizes or ranges.
 */
#ifndef NE_FONTS_H
#define NE_FONTS_H

#include "lvgl/lvgl.h"

/* lv_font_conv compresses the bitmaps; without this LVGL logs a warning and
 * draws every glyph blank, so fail the build instead. */
#if LV_USE_FONT_COMPRESSED == 0
#error "The device UI fonts are compressed: set LV_USE_FONT_COMPRESSED 1 in lv_conf.h (docs/spec/ui.md §5)"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Captions, keys and footers. */
LV_FONT_DECLARE(ne_font_12);
/* Body: labels, data, wrapped replies. */
LV_FONT_DECLARE(ne_font_16);
/* Titles and the big value of a reading. */
LV_FONT_DECLARE(ne_font_22);

#ifdef __cplusplus
}
#endif

#endif /* NE_FONTS_H */
