/* Generated by `neuroedge build --target esp32s3` from home-voice@0.1.0 — do not edit. */
/* The agent's tables (ne_agent.h). */
#include "ne_agent.h"

#include <stddef.h>

#include "gates/light_on.netree.h"
#include "gates/light_off.netree.h"

static const ne_fact ne_agent_baseline_0[1] = {{1u, 1u, 0u, 1u, 1.0}};
static const ne_fact ne_agent_baseline_1[2] = {{1u, 1u, 0u, 1u, 1.0}, {1u, 1u, 1u, 1u, 1.0}};

static const ne_agent_gate ne_agent_gate_table[2] = {
    {"light_on@1.0.0", ne_tree_light_on, (uint32_t)sizeof ne_tree_light_on,
     {0x4c, 0xc8, 0xad, 0x90, 0x1d, 0x16, 0x46, 0x52, 0xb7, 0x8c, 0xaf, 0xf9, 0x0b, 0x93, 0xd6, 0xa5, 0x43, 0xab, 0xbf, 0x6c, 0x11, 0x4e, 0x45, 0xb7, 0xf3, 0xf3, 0x74, 0x28, 0xc4, 0x47, 0x91, 0x79},
     1u, {NULL, NULL, NULL}, ne_agent_baseline_0, NULL},
    {"light_off@1.0.0", ne_tree_light_off, (uint32_t)sizeof ne_tree_light_off,
     {0x4e, 0xba, 0x33, 0x02, 0x4d, 0x53, 0x60, 0xc5, 0xaa, 0x5f, 0x6b, 0x82, 0x98, 0xc2, 0x38, 0x64, 0x09, 0x29, 0xef, 0xa3, 0xf9, 0x17, 0x2e, 0xb2, 0x92, 0xde, 0xa1, 0xb8, 0xeb, 0x9f, 0xb3, 0xd9},
     2u, {NULL, "V\341\272\253n c\303\262n ng\306\260\341\273\235i trong ph\303\262ng \342\200\224 b\341\272\241n ch\341\272\257c mu\341\273\221n t\341\272\257t \304\221\303\250n\?", NULL}, ne_agent_baseline_1, NULL},
};

static const char *const ne_agent_pin_table[1] = {
    "porch_light",
};

static const ne_agent_action ne_agent_action_table[2] = {
    {"light_off", 1u, 0x1u},
    {"light_on", 0u, 0x1u},
};

static const ne_agent_check ne_agent_check_table[26] = {
    /* light_on@1.0.0 */
    {0u, 255u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, {0u, 0u, 0u, 0u, 0.0}}, /* baseline */
    {0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, {1u, 1u, 1u, 1u, 1.0}}, /* call_source = mcp */
    {0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, {1u, 1u, 2u, 1u, 1.0}}, /* call_source = system_one */
    {0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, {1u, 1u, 3u, 1u, 1.0}}, /* call_source = system_two */
    {0u, 0u, 0u, 0u, 1u, 1u, 1u, 0u, 0u, 0u, 0x0u, {1u, 1u, 4u, 1u, 1.0}}, /* call_source = test */
    {0u, 0u, 0u, 0u, 1u, 2u, 1u, 0u, 0u, 0u, 0x0u, {0u, 0u, 0u, 0u, 0.0}}, /* call_source missing */
    {0u, 0u, 0u, 0u, 1u, 2u, 1u, 0u, 0u, 0u, 0x0u, {1u, 0u, 0u, 1u, 1.0}}, /* call_source outside its domain */
    {0u, 0u, 0u, 1u, 1u, 5u, 0u, 0u, 0u, 2u, 0x0u, {0u, 0u, 0u, 0u, 0.0}}, /* a fact missing and its source offline */
    /* light_off@1.0.0 */
    {1u, 255u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, {0u, 0u, 0u, 0u, 0.0}}, /* baseline */
    {1u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, {1u, 1u, 1u, 1u, 1.0}}, /* call_source = mcp */
    {1u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, {1u, 1u, 2u, 1u, 1.0}}, /* call_source = system_one */
    {1u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, {1u, 1u, 3u, 1u, 1.0}}, /* call_source = system_two */
    {1u, 0u, 0u, 0u, 1u, 1u, 1u, 0u, 0u, 0u, 0x0u, {1u, 1u, 4u, 1u, 1.0}}, /* call_source = test */
    {1u, 0u, 0u, 0u, 1u, 2u, 1u, 0u, 0u, 0u, 0x0u, {0u, 0u, 0u, 0u, 0.0}}, /* call_source missing */
    {1u, 0u, 0u, 0u, 1u, 2u, 1u, 0u, 0u, 0u, 0x0u, {1u, 0u, 0u, 1u, 1.0}}, /* call_source outside its domain */
    {1u, 1u, 0u, 0u, 1u, 1u, 1u, 1u, 1u, 0u, 0x0u, {1u, 1u, 0u, 1u, 1.0}}, /* room_empty = false */
    {1u, 1u, 0u, 0u, 1u, 2u, 1u, 1u, 1u, 0u, 0x0u, {0u, 0u, 0u, 0u, 0.0}}, /* room_empty missing */
    {1u, 1u, 0u, 0u, 1u, 2u, 1u, 1u, 1u, 0u, 0x0u, {1u, 0u, 0u, 1u, 1.0}}, /* room_empty outside its domain */
    {1u, 0u, 0u, 1u, 1u, 5u, 0u, 0u, 0u, 2u, 0x0u, {0u, 0u, 0u, 0u, 0.0}}, /* a fact missing and its source offline */
    {1u, 255u, 1u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x2u, {0u, 0u, 0u, 0u, 0.0}}, /* baseline, confirmed */
    {1u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x2u, {1u, 1u, 1u, 1u, 1.0}}, /* call_source = mcp, confirmed */
    {1u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x2u, {1u, 1u, 2u, 1u, 1.0}}, /* call_source = system_one, confirmed */
    {1u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x2u, {1u, 1u, 3u, 1u, 1.0}}, /* call_source = system_two, confirmed */
    {1u, 1u, 1u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x2u, {1u, 1u, 0u, 1u, 1.0}}, /* room_empty = false, confirmed */
    {1u, 1u, 1u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x2u, {0u, 0u, 0u, 0u, 0.0}}, /* room_empty missing, confirmed */
    {1u, 1u, 1u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x2u, {1u, 0u, 0u, 1u, 1.0}}, /* room_empty outside its domain, confirmed */
};

const ne_agent ne_agent_linked = {
    NE_AGENT_VERSION, NE_AGENT_BOARD,
    ne_agent_gate_table, 2u,
    ne_agent_pin_table, 1u,
    ne_agent_action_table, 2u,
    ne_agent_check_table, 26u,
};
