/* Generated by `neuroedge build --target esp32s3` from home-voice@0.1.0 — do not edit. */
/* Criterion, domain and pin positions of this agent, for code written against it */
/* (the firmware's host tests). The firmware itself never includes this header. */
#ifndef NE_AGENT_INDICES_H
#define NE_AGENT_INDICES_H
#define NE_GATE_LIGHT_ON_GATE "light_on@1.0.0"
#define NE_GATE_LIGHT_ON_ON_BLOCK_TEXT {NULL, NULL, NULL}
#define NE_GATE_LIGHT_ON_NODES 1u
#define NE_GATE_LIGHT_ON_CALL_SOURCE 0u
#define NE_GATE_LIGHT_ON_CALL_SOURCE_LOCAL_GRAMMAR 0u
#define NE_GATE_LIGHT_ON_CALL_SOURCE_MCP 1u
#define NE_GATE_LIGHT_ON_CALL_SOURCE_SYSTEM_ONE 2u
#define NE_GATE_LIGHT_ON_CALL_SOURCE_SYSTEM_TWO 3u
#define NE_GATE_LIGHT_ON_CALL_SOURCE_TEST 4u
#define NE_GATE_LIGHT_OFF_GATE "light_off@1.0.0"
#define NE_GATE_LIGHT_OFF_ON_BLOCK_TEXT {NULL, "V\341\272\253n c\303\262n ng\306\260\341\273\235i trong ph\303\262ng \342\200\224 b\341\272\241n ch\341\272\257c mu\341\273\221n t\341\272\257t \304\221\303\250n\?", NULL}
#define NE_GATE_LIGHT_OFF_NODES 2u
#define NE_GATE_LIGHT_OFF_CALL_SOURCE 0u
#define NE_GATE_LIGHT_OFF_CALL_SOURCE_LOCAL_GRAMMAR 0u
#define NE_GATE_LIGHT_OFF_CALL_SOURCE_MCP 1u
#define NE_GATE_LIGHT_OFF_CALL_SOURCE_SYSTEM_ONE 2u
#define NE_GATE_LIGHT_OFF_CALL_SOURCE_SYSTEM_TWO 3u
#define NE_GATE_LIGHT_OFF_CALL_SOURCE_TEST 4u
#define NE_GATE_LIGHT_OFF_ROOM_EMPTY 1u
#define NE_GATE_LIGHT_OFF_ROOM_EMPTY_FALSE 0u
#define NE_GATE_LIGHT_OFF_ROOM_EMPTY_TRUE 1u
#define NE_PIN_PORCH_LIGHT 0u
#endif /* NE_AGENT_INDICES_H */
