/* Generated by `neuroedge build --target esp32s3` from home-voice@0.1.0 — do not edit. */
/*
 * The agent linked into this image (TSK-I3-01): its gates as NETR v1 trees in flash,
 * its digital.out pins, its @actions with the gate and pins of each, and the checks
 * the boot self-test decides with the C walker (main/gate_selftest.c). Every expected
 * verdict is the host engine's (python/neuroedge/engine/gate.py) for the same facts.
 */
#ifndef NE_AGENT_H
#define NE_AGENT_H

#include <stdint.h>

#include "ne_trace.h"
#include "ne_walker.h"

#ifdef __cplusplus
extern "C" {
#endif

#define NE_AGENT_VERSION "home-voice@0.1.0"
#define NE_AGENT_BOARD "esp32s3-box-3"
/* The most criteria of any gate of this agent: the self-test's fact buffer. */
#define NE_AGENT_MAX_NODES 2u
#define NE_AGENT_NO_NODE 255u

typedef struct {
    const char *label;          /* "light_on@1.0.0" */
    const uint8_t *tree;        /* NETR v1 bytes, in flash */
    uint32_t tree_size;
    uint8_t digest[32];         /* the gate digest the host compiled the tree from */
    uint16_t node_count;
    ne_on_block_text text;      /* what NETR v1 does not carry (TODOS.md #36) */
    const ne_fact *baseline;    /* self-test: one fact per criterion */
    const ne_arg_value *args;   /* self-test: one value per argument limit, or NULL */
} ne_agent_gate;

typedef struct {
    const char *name;           /* the @action */
    uint16_t gate;              /* index into gates: the gate that guards it */
    uint32_t pin_mask;          /* bit i = pins[i]: what a token for it may drive */
} ne_agent_action;

typedef struct {
    uint16_t gate;              /* index into gates */
    uint8_t node;               /* the criterion this check varies, or NE_AGENT_NO_NODE */
    uint8_t confirmed;          /* a person said "co" (RFC-0006) */
    uint8_t degraded;           /* ne_degraded */
    /* The host engine's answer, field by field as ne_result has it. */
    uint8_t verdict;
    uint8_t reason;
    uint8_t failed_kind;
    uint8_t failed_index;
    uint8_t answerable;
    uint8_t fail_mode;
    uint32_t confirmed_mask;
    ne_fact fact;               /* the fact of `node` (present 0: removed) */
} ne_agent_check;

typedef struct {
    const char *version;
    const char *board;
    const ne_agent_gate *gates;
    uint32_t gate_count;
    const char *const *pins;
    uint32_t pin_count;
    const ne_agent_action *actions;
    uint32_t action_count;
    const ne_agent_check *checks;
    uint32_t check_count;
} ne_agent;

/* The agent this image was built for. */
extern const ne_agent ne_agent_linked;

#ifdef __cplusplus
}
#endif

#endif /* NE_AGENT_H */
