/* Generated by `neuroedge build --target esp32s3` from firmware-fixture@0.2.0 — do not edit. */
/* The agent's tables (ne_agent.h). */
#include "ne_agent.h"

#include <stddef.h>

#include "gates/open_door.netree.h"
#include "gates/buzz.netree.h"
#include "gates/announce.netree.h"

static const ne_fact ne_agent_baseline_0[4] = {{1u, 1u, 1u, 1u, 1.0}, {1u, 1u, 0u, 1u, 1.0}, {1u, 1u, 0u, 1u, 1.0}, {1u, 1u, 1u, 1u, 1.0}};
static const ne_fact ne_agent_baseline_1[1] = {{1u, 1u, 1u, 1u, 1.0}};
static const ne_arg_value ne_agent_args_1[2] = {{1u, 1u, 0u, NULL, 1.0}, {1u, 0u, 5u, "front", 0.0}};
static const ne_fact ne_agent_baseline_2[1] = {{1u, 1u, 0u, 1u, 1.0}};

static const ne_agent_gate ne_agent_gate_table[3] = {
    {"open_door@1.0.0", ne_tree_open_door, (uint32_t)sizeof ne_tree_open_door,
     {0x70, 0xc1, 0xd4, 0xb1, 0x53, 0x87, 0xd4, 0xfd, 0x9b, 0x3d, 0xe5, 0xb1, 0x40, 0x36, 0xe7, 0x0c, 0x70, 0x17, 0x31, 0x23, 0xc8, 0xc5, 0x3e, 0x73, 0x43, 0x30, 0x12, 0xa5, 0x84, 0x0a, 0xa0, 0x90},
     4u, {NULL, "Ch\341\273\247 nh\303\240 kh\303\264ng c\303\263 \341\273\237 nh\303\240 \342\200\224 v\341\272\253n m\341\273\237 c\341\273\255a\?", NULL}, ne_agent_baseline_0, NULL},
    {"buzz@1.0.0", ne_tree_buzz, (uint32_t)sizeof ne_tree_buzz,
     {0x10, 0xfa, 0x42, 0xe0, 0x2b, 0x15, 0x88, 0xc4, 0xcb, 0x77, 0xe8, 0x00, 0xa4, 0x4e, 0x6f, 0x02, 0x8f, 0x3b, 0x08, 0x62, 0x67, 0xc8, 0x3a, 0xfe, 0x8a, 0x72, 0x3d, 0x36, 0xe1, 0xa7, 0x01, 0xb8},
     1u, {NULL, NULL, NULL}, ne_agent_baseline_1, ne_agent_args_1},
    {"announce@1.0.0", ne_tree_announce, (uint32_t)sizeof ne_tree_announce,
     {0x22, 0x2c, 0xe6, 0x4e, 0x4b, 0xed, 0xe4, 0xea, 0x2a, 0x1c, 0x89, 0xef, 0xf8, 0x19, 0xda, 0x2e, 0x72, 0xb2, 0x9d, 0x00, 0x15, 0x8a, 0x3f, 0x44, 0x44, 0x8b, 0x7b, 0x56, 0x1b, 0xbd, 0x17, 0x4d},
     1u, {"front_desk", "Gi\341\273\235 y\303\252n l\341\272\267ng */ kh\303\264ng ph\303\241t th\303\264ng b\303\241o.", NULL}, ne_agent_baseline_2, NULL},
};

static const char *const ne_agent_pin_table[3] = {
    "door_lock",
    "gate_relay",
    "porch_light",
};

static const ne_agent_action ne_agent_action_table[3] = {
    {"fixture_announce", 2u, 0x0u},
    {"fixture_buzz", 1u, 0x2u},
    {"fixture_open_door", 0u, 0x3u},
};

static const ne_agent_check ne_agent_check_table[37] = {
    /* open_door@1.0.0 */
    {0u, 255u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, {0u, 0u, 0u, 0u, 0.0}}, /* baseline */
    {0u, 0u, 0u, 0u, 1u, 1u, 1u, 0u, 1u, 0u, 0x0u, {1u, 1u, 0u, 1u, 1.0}}, /* resident_home = false */
    {0u, 0u, 0u, 0u, 1u, 2u, 1u, 0u, 1u, 0u, 0x0u, {0u, 0u, 0u, 0u, 0.0}}, /* resident_home missing */
    {0u, 0u, 0u, 0u, 1u, 2u, 1u, 0u, 1u, 0u, 0x0u, {1u, 0u, 0u, 1u, 1.0}}, /* resident_home outside its domain */
    {0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, {1u, 1u, 1u, 1u, 1.0}}, /* risk = medium */
    {0u, 1u, 0u, 0u, 1u, 1u, 1u, 1u, 0u, 0u, 0x0u, {1u, 1u, 2u, 1u, 1.0}}, /* risk = high */
    {0u, 1u, 0u, 0u, 1u, 2u, 1u, 1u, 0u, 0u, 0x0u, {0u, 0u, 0u, 0u, 0.0}}, /* risk missing */
    {0u, 1u, 0u, 0u, 1u, 2u, 1u, 1u, 0u, 0u, 0x0u, {1u, 0u, 0u, 1u, 1.0}}, /* risk outside its domain */
    {0u, 2u, 0u, 0u, 1u, 1u, 1u, 2u, 0u, 0u, 0x0u, {1u, 1u, 1u, 1u, 1.0}}, /* channel = mcp */
    {0u, 2u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, {1u, 1u, 2u, 1u, 1.0}}, /* channel = voice */
    {0u, 2u, 0u, 0u, 1u, 2u, 1u, 2u, 0u, 0u, 0x0u, {0u, 0u, 0u, 0u, 0.0}}, /* channel missing */
    {0u, 2u, 0u, 0u, 1u, 2u, 1u, 2u, 0u, 0u, 0x0u, {1u, 0u, 0u, 1u, 1.0}}, /* channel outside its domain */
    {0u, 3u, 0u, 0u, 1u, 1u, 1u, 3u, 0u, 0u, 0x0u, {1u, 1u, 0u, 1u, 1.0}}, /* face_match = false */
    {0u, 3u, 0u, 0u, 1u, 2u, 1u, 3u, 0u, 0u, 0x0u, {0u, 0u, 0u, 0u, 0.0}}, /* face_match missing */
    {0u, 3u, 0u, 0u, 1u, 2u, 1u, 3u, 0u, 0u, 0x0u, {1u, 0u, 0u, 1u, 1.0}}, /* face_match outside its domain */
    {0u, 3u, 0u, 0u, 1u, 3u, 1u, 3u, 0u, 0u, 0x0u, {1u, 1u, 1u, 0u, 0.0}}, /* face_match: no confidence */
    {0u, 3u, 0u, 0u, 1u, 1u, 1u, 3u, 0u, 0u, 0x0u, {1u, 1u, 1u, 1u, 0.899}}, /* face_match: confidence below the floor */
    {0u, 3u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, {1u, 1u, 1u, 1u, 0.9}}, /* face_match: confidence at the floor */
    {0u, 3u, 0u, 0u, 1u, 2u, 1u, 3u, 0u, 0u, 0x0u, {1u, 1u, 1u, 1u, 1.5}}, /* face_match: confidence outside [0, 1] */
    {0u, 0u, 0u, 1u, 1u, 5u, 0u, 0u, 0u, 2u, 0x0u, {0u, 0u, 0u, 0u, 0.0}}, /* a fact missing and its source offline */
    {0u, 255u, 1u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x1u, {0u, 0u, 0u, 0u, 0.0}}, /* baseline, confirmed */
    {0u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x1u, {1u, 1u, 0u, 1u, 1.0}}, /* resident_home = false, confirmed */
    {0u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x1u, {0u, 0u, 0u, 0u, 0.0}}, /* resident_home missing, confirmed */
    {0u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x1u, {1u, 0u, 0u, 1u, 1.0}}, /* resident_home outside its domain, confirmed */
    {0u, 1u, 1u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x1u, {1u, 1u, 1u, 1u, 1.0}}, /* risk = medium, confirmed */
    {0u, 2u, 1u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x1u, {1u, 1u, 2u, 1u, 1.0}}, /* channel = voice, confirmed */
    {0u, 3u, 1u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x1u, {1u, 1u, 1u, 1u, 0.9}}, /* face_match: confidence at the floor, confirmed */
    /* buzz@1.0.0 */
    {1u, 255u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, {0u, 0u, 0u, 0u, 0.0}}, /* baseline */
    {1u, 0u, 0u, 0u, 1u, 1u, 1u, 0u, 0u, 0u, 0x0u, {1u, 1u, 0u, 1u, 1.0}}, /* visitor_expected = false */
    {1u, 0u, 0u, 0u, 1u, 2u, 1u, 0u, 0u, 0u, 0x0u, {0u, 0u, 0u, 0u, 0.0}}, /* visitor_expected missing */
    {1u, 0u, 0u, 0u, 1u, 2u, 1u, 0u, 0u, 0u, 0x0u, {1u, 0u, 0u, 1u, 1.0}}, /* visitor_expected outside its domain */
    {1u, 0u, 0u, 1u, 0u, 5u, 0u, 0u, 0u, 1u, 0x0u, {0u, 0u, 0u, 0u, 0.0}}, /* a fact missing and its source offline */
    /* announce@1.0.0 */
    {2u, 255u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x0u, {0u, 0u, 0u, 0u, 0.0}}, /* baseline */
    {2u, 0u, 0u, 0u, 1u, 1u, 1u, 0u, 0u, 0u, 0x0u, {1u, 1u, 1u, 1u, 1.0}}, /* quiet_hours = true */
    {2u, 0u, 0u, 0u, 1u, 2u, 1u, 0u, 0u, 0u, 0x0u, {0u, 0u, 0u, 0u, 0.0}}, /* quiet_hours missing */
    {2u, 0u, 0u, 0u, 1u, 2u, 1u, 0u, 0u, 0u, 0x0u, {1u, 0u, 0u, 1u, 1.0}}, /* quiet_hours outside its domain */
    {2u, 0u, 0u, 1u, 1u, 5u, 0u, 0u, 0u, 2u, 0x0u, {0u, 0u, 0u, 0u, 0.0}}, /* a fact missing and its source offline */
};

const ne_agent ne_agent_linked = {
    NE_AGENT_VERSION, NE_AGENT_BOARD,
    ne_agent_gate_table, 3u,
    ne_agent_pin_table, 3u,
    ne_agent_action_table, 3u,
    ne_agent_check_table, 37u,
};
