/*
 * Boot self-test of the gate runtime — see gate_selftest.h.
 *
 * Nothing here knows which agent it tests: the gates, pins, actions and the
 * host engine's expected verdicts all come from `ne_agent` (components/ne_agent/,
 * generated by `neuroedge build --target esp32s3`). A disagreement stops the
 * self-test at the first check that differs, and names it.
 */
#include "gate_selftest.h"

#include <stdio.h>
#include <string.h>

#include "ne_walker.h"

static int fail(char *line, size_t cap, const char *what, const char *name) {
    snprintf(line, cap, "NE_SELFTEST FAIL %s %s", what, name != NULL ? name : "");
    return 1;
}

/* The gate's tree from flash, checked against what the host compiled. */
static int load(const ne_agent_gate *g, ne_tree *tree) {
    if (g->tree == NULL || g->baseline == NULL ||
        ne_tree_load(tree, g->tree, g->tree_size) != NE_OK)
        return 0;
    if (tree->node_count != g->node_count || tree->node_count > NE_AGENT_MAX_NODES) return 0;
    if (tree->arg_count > 0u && g->args == NULL) return 0;
    return memcmp(tree->gate_digest, g->digest, sizeof g->digest) == 0;
}

/* One check: the baseline facts, one criterion varied, decided and compared field by field. */
static int decided(const ne_agent_gate *g, const ne_tree *tree, const ne_agent_check *k,
                   ne_trace_sink *sink) {
    ne_fact facts[NE_AGENT_MAX_NODES];
    ne_result r;
    memcpy(facts, g->baseline, tree->node_count * sizeof facts[0]);
    if (k->node != NE_AGENT_NO_NODE) {
        if (k->node >= tree->node_count) return 0;
        facts[k->node] = k->fact;
    }
    if (sink != NULL) {
        ne_trace_put(sink, ne_trace_gate_begin(sink->buf, sink->cap, ne_trace_offset(sink),
                                               g->label, tree));
        ne_trace_put(sink, ne_trace_gate_facts(sink->buf, sink->cap, ne_trace_offset(sink), tree,
                                               facts, NULL));
    }
    if (ne_decide(tree, facts, g->args, k->confirmed, (ne_degraded)k->degraded, &r) != NE_OK)
        return 0;
    if (sink != NULL)
        ne_trace_put(sink, ne_trace_gate_result(sink->buf, sink->cap, ne_trace_offset(sink),
                                                g->label, tree, facts, &r, &g->text));
    return (uint8_t)r.verdict == k->verdict && (uint8_t)r.reason == k->reason &&
           (uint8_t)r.failed_kind == k->failed_kind && r.failed_index == k->failed_index &&
           r.answerable == k->answerable && r.fail_mode == k->fail_mode &&
           r.confirmed_mask == k->confirmed_mask;
}

/* The action's token: its pins once each, nothing else, and not after tampering. */
static int granted(const ne_agent *agent, const ne_agent_action *a, const ne_tree *tree,
                   ne_random_fn fill_random, uint32_t boot_id, uint32_t now_ms, unsigned *passed) {
    ne_ledger ledger;
    ne_token t, spare;
    if (ne_ledger_init(&ledger, boot_id) != NE_TOKEN_OK ||
        ne_token_issue(&ledger, tree, a->pin_mask, now_ms, fill_random, &t) != NE_TOKEN_OK)
        return 0;
    (*passed)++;
    /* One past the table too: a pin the agent does not have is never granted. */
    const uint32_t last = agent->pin_count < NE_MAX_PINS ? agent->pin_count : NE_MAX_PINS - 1u;
    for (uint32_t pin = 0; pin <= last; pin++) {
        if ((a->pin_mask >> pin) & 1u) {
            if (ne_token_authorize(&ledger, &t, pin, now_ms) != NE_TOKEN_AUTHORIZED) return 0;
            if (ne_token_authorize(&ledger, &t, pin, now_ms) != NE_TOKEN_REPLAYED) return 0;
            *passed += 2u;
        } else {
            if (ne_token_authorize(&ledger, &t, pin, now_ms) != NE_TOKEN_PIN_NOT_GRANTED) return 0;
            (*passed)++;
        }
    }
    spare = t;
    spare.nonce[0] ^= 1u;
    if (ne_token_authorize(&ledger, &spare, 0u, now_ms) != NE_TOKEN_UNKNOWN_TOKEN) return 0;
    (*passed)++;
    ne_token_close(&ledger, &t);
    return 1;
}

int neuroedge_gate_selftest(const ne_agent *agent, ne_random_fn fill_random, uint32_t boot_id,
                            uint32_t now_ms, char *line, size_t cap, ne_trace_sink *sink) {
    ne_tree tree;
    unsigned walker = 0, token = 0;

    if (line == NULL || cap == 0) return 1;
    if (agent == NULL || fill_random == NULL) return fail(line, cap, "no agent", NULL);
    if (agent->pin_count > NE_MAX_PINS || (agent->gate_count > 0u && agent->gates == NULL) ||
        (agent->pin_count > 0u && agent->pins == NULL) ||
        (agent->action_count > 0u && agent->actions == NULL) ||
        (agent->check_count > 0u && agent->checks == NULL))
        return fail(line, cap, "agent tables", agent->version);

    /* 1. Every tree in flash is the one the host compiled for its gate. */
    for (uint32_t i = 0; i < agent->gate_count; i++)
        if (!load(&agent->gates[i], &tree)) return fail(line, cap, "load", agent->gates[i].label);

    /* 2. The walker decides every check as the host engine did. */
    for (uint32_t i = 0; i < agent->check_count; i++) {
        const ne_agent_check *k = &agent->checks[i];
        if (k->gate >= agent->gate_count) return fail(line, cap, "check table", agent->version);
        const ne_agent_gate *g = &agent->gates[k->gate];
        if (!load(g, &tree) || !decided(g, &tree, k, sink)) {
            char what[24];
            snprintf(what, sizeof what, "check %u", (unsigned)i);
            return fail(line, cap, what, g->label);
        }
        walker++;
    }

    /* 3. A token for an action drives exactly the action's pins, once each. */
    const uint32_t pins = agent->pin_count == NE_MAX_PINS ? UINT32_MAX : (1u << agent->pin_count) - 1u;
    for (uint32_t i = 0; i < agent->action_count; i++) {
        const ne_agent_action *a = &agent->actions[i];
        if (a->gate >= agent->gate_count || (a->pin_mask & ~pins) != 0u)
            return fail(line, cap, "action table", a->name);
        if (!load(&agent->gates[a->gate], &tree) ||
            !granted(agent, a, &tree, fill_random, boot_id, now_ms, &token))
            return fail(line, cap, "token", a->name);
    }

    /* 4. Closed slots are reused; live tokens fill the ledger, and it fails closed. */
    if (agent->gate_count > 0u) {
        ne_ledger ledger;
        ne_token held, spare;
        if (!load(&agent->gates[0], &tree) || ne_ledger_init(&ledger, boot_id) != NE_TOKEN_OK ||
            ne_token_issue(&ledger, &tree, 1u, now_ms, fill_random, &held) != NE_TOKEN_OK)
            return fail(line, cap, "ledger", "slot not issued");
        for (uint32_t i = 1; i < NE_TOKEN_SLOTS; i++)
            if (ne_token_issue(&ledger, &tree, 1u, now_ms, fill_random, &spare) != NE_TOKEN_OK)
                return fail(line, cap, "ledger", "slot not issued");
        if (ne_token_issue(&ledger, &tree, 1u, now_ms, fill_random, &spare) != NE_TOKEN_ERR_FULL)
            return fail(line, cap, "ledger", "full ledger did not fail closed");
        ne_token_close(&ledger, &held);
        if (ne_token_issue(&ledger, &tree, 1u, now_ms, fill_random, &spare) != NE_TOKEN_OK)
            return fail(line, cap, "ledger", "closed slot not reused");
        token++;
    }

    snprintf(line, cap, "NE_SELFTEST PASS walker=%u token=%u", walker, token);
    return 0;
}
