/*
 * Boot self-test of the gate runtime (TSK-S4-02, TSK-S4-08).
 *
 * Loads the home-voice gates linked into flash (main/gates/, generated by
 * scripts/gen_firmware_gates.py), decides a few truth-table rows with the C
 * walker, and runs one token through the ledger: issued, authorised once,
 * refused as `token_replayed` the second time. Pure C99 with no ESP-IDF
 * dependency, so python/tests/test_c_token.py also runs it on the host.
 *
 * With a trace sink, every gate evaluation is also written as `NE1` trace
 * lines (gate_evaluation_begin, gate_facts, gate_evaluation_result — TSK-S4-09)
 * inside the caller's session; token checks write none.
 */
#ifndef NEUROEDGE_GATE_SELFTEST_H
#define NEUROEDGE_GATE_SELFTEST_H

#include <stddef.h>
#include <stdint.h>

#include "ne_token.h"
#include "ne_trace.h"

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Returns 0 when every check passed. `line` receives the one line the firmware
 * prints on the UART, which the QEMU job greps for:
 *   "NE_SELFTEST PASS walker=<n> token=<n>"   n = checks passed
 *   "NE_SELFTEST FAIL <what>"
 * `sink` may be NULL: nothing but `line` is written.
 */
int neuroedge_gate_selftest(ne_random_fn fill_random, uint32_t boot_id, uint32_t now_ms,
                            char *line, size_t cap, ne_trace_sink *sink);

#ifdef __cplusplus
}
#endif

#endif /* NEUROEDGE_GATE_SELFTEST_H */
