/* Generated by scripts/gen_firmware_gates.py from fixtures/agents/home-voice — do not edit. */
/* Criterion positions, domain positions and pin numbers the gate self-test uses, */
/* and the labels and on_block texts its trace lines carry (NETR v1 has neither). */
#ifndef NE_HOME_VOICE_INDICES_H
#define NE_HOME_VOICE_INDICES_H
#define NE_AGENT_VERSION "home-voice@0.1.0"
/* light_on@1.0.0 · sha256:4cc8ad901d164652b78caff90b93d6a543abbf6c114e45b7f3f37428c4479179 */
#define NE_LIGHT_ON_GATE "light_on@1.0.0"
#define NE_LIGHT_ON_ON_BLOCK_TEXT {NULL, NULL, NULL}
#define NE_LIGHT_ON_NODES 1u
#define NE_LIGHT_ON_CALL_SOURCE 0u
#define NE_LIGHT_ON_CALL_SOURCE_LOCAL_GRAMMAR 0u
#define NE_LIGHT_ON_CALL_SOURCE_MCP 1u
#define NE_LIGHT_ON_CALL_SOURCE_SYSTEM_ONE 2u
#define NE_LIGHT_ON_CALL_SOURCE_SYSTEM_TWO 3u
#define NE_LIGHT_ON_CALL_SOURCE_TEST 4u
/* light_off@1.0.0 · sha256:4eba33024d5360c5aa5f6b8298c238640929efa3f9172eb292dea1b8eb9fb3d9 */
#define NE_LIGHT_OFF_GATE "light_off@1.0.0"
#define NE_LIGHT_OFF_ON_BLOCK_TEXT {NULL, "V\341\272\253n c\303\262n ng\306\260\341\273\235i trong ph\303\262ng \342\200\224 b\341\272\241n ch\341\272\257c mu\341\273\221n t\341\272\257t \304\221\303\250n\?", NULL}
#define NE_LIGHT_OFF_NODES 2u
#define NE_LIGHT_OFF_CALL_SOURCE 0u
#define NE_LIGHT_OFF_CALL_SOURCE_LOCAL_GRAMMAR 0u
#define NE_LIGHT_OFF_CALL_SOURCE_MCP 1u
#define NE_LIGHT_OFF_CALL_SOURCE_SYSTEM_ONE 2u
#define NE_LIGHT_OFF_CALL_SOURCE_SYSTEM_TWO 3u
#define NE_LIGHT_OFF_CALL_SOURCE_TEST 4u
#define NE_LIGHT_OFF_ROOM_EMPTY 1u
#define NE_LIGHT_OFF_ROOM_EMPTY_FALSE 0u
#define NE_LIGHT_OFF_ROOM_EMPTY_TRUE 1u
#define NE_PIN_PORCH_LIGHT 0u
#endif /* NE_HOME_VOICE_INDICES_H */
