/* Generated by scripts/gen_firmware_gates.py from fixtures/agents/home-voice — do not edit. */
/* Criterion positions, domain positions and pin numbers the gate self-test uses. */
#ifndef NE_HOME_VOICE_INDICES_H
#define NE_HOME_VOICE_INDICES_H
/* light_on@1.0.0 · sha256:4cc8ad901d164652b78caff90b93d6a543abbf6c114e45b7f3f37428c4479179 */
#define NE_LIGHT_ON_NODES 1u
#define NE_LIGHT_ON_CALL_SOURCE 0u
#define NE_LIGHT_ON_CALL_SOURCE_LOCAL_GRAMMAR 0u
#define NE_LIGHT_ON_CALL_SOURCE_MCP 1u
#define NE_LIGHT_ON_CALL_SOURCE_SYSTEM_ONE 2u
#define NE_LIGHT_ON_CALL_SOURCE_SYSTEM_TWO 3u
#define NE_LIGHT_ON_CALL_SOURCE_TEST 4u
/* light_off@1.0.0 · sha256:4eba33024d5360c5aa5f6b8298c238640929efa3f9172eb292dea1b8eb9fb3d9 */
#define NE_LIGHT_OFF_NODES 2u
#define NE_LIGHT_OFF_CALL_SOURCE 0u
#define NE_LIGHT_OFF_CALL_SOURCE_LOCAL_GRAMMAR 0u
#define NE_LIGHT_OFF_CALL_SOURCE_MCP 1u
#define NE_LIGHT_OFF_CALL_SOURCE_SYSTEM_ONE 2u
#define NE_LIGHT_OFF_CALL_SOURCE_SYSTEM_TWO 3u
#define NE_LIGHT_OFF_CALL_SOURCE_TEST 4u
#define NE_LIGHT_OFF_ROOM_EMPTY 1u
#define NE_LIGHT_OFF_ROOM_EMPTY_FALSE 0u
#define NE_LIGHT_OFF_ROOM_EMPTY_TRUE 1u
#define NE_PIN_PORCH_LIGHT 0u
#endif /* NE_HOME_VOICE_INDICES_H */
