#!/usr/bin/env bash
#
# Generate the LVGL fonts of the device UI (TSK-S4-10) into
# targets/esp32s3/ui/fonts/. Run from anywhere; the output is byte-identical
# for the same pins:
#
#     bash scripts/gen_ui_fonts.sh
#
# Source: Be Vietnam Pro (OFL-1.1, LICENSES/OFL-1.1.txt; NOTICE section A.5),
# by the Be Vietnam Pro Project Authors. The upstream files are pinned by URL
# and SHA-256 below and fetched into .cache/ (git-ignored); the generated .c
# files carry the attribution in their header, as CONTRIBUTING.md §4
# obligation 3 asks. lv_font_conv is pinned at 1.5.3; Node runs it through npx.
#
# The ranges both languages need are one list: fonts/ranges.txt.
# python/tests/test_ui_assets.py checks every character of the string tables is
# inside them; add a range there and rerun this script when a string needs it.
set -euo pipefail

ROOT=$(cd "$(dirname "$0")/.." && pwd)
FONTS="$ROOT/targets/esp32s3/ui/fonts"
CACHE="${NE_UI_FONT_CACHE:-$ROOT/.cache/ui-fonts}"
LV_FONT_CONV="lv_font_conv@1.5.3"
BPP=4
VERIFIED="2026-09-26"

REGULAR_URL="https://raw.githubusercontent.com/google/fonts/main/ofl/bevietnampro/BeVietnamPro-Regular.ttf"
REGULAR_SHA="cd1ef6e9d7db28ad5cdb88a65ccbe693870e60d340b791f349d248342b4fe4c3"
SEMIBOLD_URL="https://raw.githubusercontent.com/google/fonts/main/ofl/bevietnampro/BeVietnamPro-SemiBold.ttf"
SEMIBOLD_SHA="bd8e27eb02720b9d91e59e4f10a90878643219f25ce6a8d9a4f06a8a88d3bb71"
OFL_URL="https://raw.githubusercontent.com/google/fonts/main/ofl/bevietnampro/OFL.txt"
OFL_SHA="6b7f8f73609a25ea78c891e34cf37b06f8a676b7ea986e941e43b009110f2a85"

mkdir -p "$CACHE" "$FONTS"

sha256() {
    if command -v shasum >/dev/null 2>&1; then
        shasum -a 256 "$1" | awk '{print $1}'
    else
        sha256sum "$1" | awk '{print $1}'
    fi
}

# fetch <url> <sha256> <name>: download once, verify every time, fail closed.
fetch() {
    local url="$1" want="$2" name="$3" path="$CACHE/$3"
    if [ ! -f "$path" ]; then
        echo "  fetching $name"
        curl --fail --silent --show-error --location --output "$path" "$url"
    fi
    local got
    got=$(sha256 "$path")
    if [ "$got" != "$want" ]; then
        echo "error: $path has SHA-256 $got, expected $want" >&2
        echo "       upstream changed; update the pin here and re-verify the licence (CONTRIBUTING.md §4)" >&2
        exit 1
    fi
}

RANGES=$(grep -v '^[[:space:]]*#' "$FONTS/ranges.txt" | tr -d ' \n')
if [ -z "$RANGES" ]; then
    echo "error: $FONTS/ranges.txt is empty" >&2
    exit 1
fi

# generate <source ttf> <source name> <sha> <size> <font name>
generate() {
    local ttf="$1" source="$2" sha="$3" size="$4" name="$5"
    local tmp="$CACHE/$name.raw.c" out="$FONTS/$name.c"
    echo "  $name: ${size}px from $source"
    npx --yes "$LV_FONT_CONV" \
        --font "$ttf" \
        --size "$size" \
        --bpp "$BPP" \
        --format lvgl \
        --lv-font-name "$name" \
        --range "$RANGES" \
        --force-fast-kern-format \
        --output "$tmp"
    # Replace lv_font_conv's banner (it embeds a machine's output path) with a
    # canonical attribution this repository can check, and keep its body as is.
    python3 - "$tmp" "$out" "$name" "$size" "$BPP" "$source" "$sha" "$VERIFIED" <<'PY'
import sys

src, dst, name, size, bpp, source, sha, verified = sys.argv[1:9]
body = open(src, encoding="utf-8").read()
marker = "#ifdef LV_LVGL_H_INCLUDE_SIMPLE"
body = body[body.index(marker):]
header = f"""\
/* Generated by scripts/gen_ui_fonts.sh — do not edit.
 *
 * {name}: {size}px, {bpp}bpp, LVGL format. Source: {source} from Be Vietnam Pro
 * (https://github.com/google/fonts/tree/main/ofl/bevietnampro), copyright 2021
 * The Be Vietnam Pro Project Authors, SIL Open Font License 1.1
 * (LICENSES/OFL-1.1.txt; NOTICE section A.5). Verified {verified},
 * file SHA-256 {sha}. Glyph ranges: fonts/ranges.txt.
 *
 * The OFL asks that the font not be sold by itself and that Modified Versions
 * keep the reserved font names; this bitmap subset is used inside NeuroEdge
 * and is not the font software. Regenerate with: bash scripts/gen_ui_fonts.sh
 */
{body}"""
open(dst, "w", encoding="utf-8").write(header)
PY
}

echo "Generating targets/esp32s3/ui/fonts/ with $LV_FONT_CONV"
fetch "$REGULAR_URL" "$REGULAR_SHA" BeVietnamPro-Regular.ttf
fetch "$SEMIBOLD_URL" "$SEMIBOLD_SHA" BeVietnamPro-SemiBold.ttf
generate "$CACHE/BeVietnamPro-Regular.ttf" "BeVietnamPro-Regular.ttf" "$REGULAR_SHA" 12 ne_font_12
generate "$CACHE/BeVietnamPro-Regular.ttf" "BeVietnamPro-Regular.ttf" "$REGULAR_SHA" 16 ne_font_16
generate "$CACHE/BeVietnamPro-SemiBold.ttf" "BeVietnamPro-SemiBold.ttf" "$SEMIBOLD_SHA" 22 ne_font_22
# The OFL text travels with the fonts it governs (CONTRIBUTING.md §4).
fetch "$OFL_URL" "$OFL_SHA" OFL.txt
cp "$CACHE/OFL.txt" "$ROOT/LICENSES/OFL-1.1.txt"
echo "Done: 3 fonts and LICENSES/OFL-1.1.txt"
