#!/usr/bin/env python3
"""Sinh targets/esp32s3/main/gates/ từ fixtures/agents/home-voice (TSK-S4-02, TSK-S4-08).

Firmware tự kiểm lúc khởi động (`main/gate_selftest.c`) chạy walker và sổ token
trên hai gate thật của agent mẫu. Cây của chúng là đầu ra của `neuroedge build`
(`<gate>.netree.h`, RFC-0003), chép nguyên văn vào `main/gates/` và commit, vì CI
firmware chỉ có ESP-IDF, không có Python của repo. Kèm `home_voice_indices.h`:
vị trí tiêu chí, vị trí giá trị trong miền và chỉ số chân, để self-test không
phải đoán thứ tự nút.

    python/.venv/bin/python scripts/gen_firmware_gates.py           # ghi tệp
    python/.venv/bin/python scripts/gen_firmware_gates.py --check   # thoát 1 nếu lệch

`python/tests/test_c_token.py` chạy `--check`: đổi gate mà quên sinh lại là fail.
"""

from __future__ import annotations

import argparse
import re
import sys
import tempfile
from pathlib import Path

from neuroedge.engine.binary_tree import c_string
from neuroedge.engine.compiler import build, load_agent_manifest
from neuroedge.engine.decision_tree import compile_tree
from neuroedge.engine.gate_resolver import resolve_gate_file
from neuroedge.paths import repo_root

ROOT = repo_root()
AGENT = ROOT / "fixtures" / "agents" / "home-voice"
TARGET = ROOT / "targets" / "esp32s3" / "main" / "gates"
GATES = ("light_on", "light_off")


def _ident(text: str) -> str:
    return re.sub(r"[^A-Z0-9]", "_", str(text).upper())


def indices_header() -> str:
    manifest = load_agent_manifest(AGENT / "agent.toml")
    lines = [
        "/* Generated by scripts/gen_firmware_gates.py from fixtures/agents/home-voice — do not edit. */",
        "/* Criterion positions, domain positions and pin numbers the gate self-test uses, */",
        "/* and the labels and on_block texts its trace lines carry (NETR v1 has neither). */",
        "#ifndef NE_HOME_VOICE_INDICES_H",
        "#define NE_HOME_VOICE_INDICES_H",
        f"#define NE_AGENT_VERSION {c_string(manifest.label)}",
    ]
    for gate in GATES:
        resolved = resolve_gate_file(AGENT / manifest.gates[gate])
        tree = compile_tree(resolved)
        prefix = f"NE_{_ident(gate)}"
        text = [
            c_string(resolved.on_block[key]) if resolved.on_block.get(key) else "NULL"
            for key in ("to", "message", "fallback_action")
        ]
        lines.append(f"/* {tree['gate']} · {tree['gate_digest']} */")
        lines.append(f"#define {prefix}_GATE {c_string(tree['gate'])}")
        lines.append(f"#define {prefix}_ON_BLOCK_TEXT {{{', '.join(text)}}}")
        lines.append(f"#define {prefix}_NODES {len(tree['nodes'])}u")
        for i, node in enumerate(tree["nodes"]):
            name = f"{prefix}_{_ident(node['criterion'])}"
            lines.append(f"#define {name} {i}u")
            for j, value in enumerate(node["domain"]):
                lines.append(f"#define {name}_{_ident(value)} {j}u")
    pins = manifest.requires["digital.out"]["pins"]
    for i, pin in enumerate(pins):
        lines.append(f"#define NE_PIN_{_ident(pin)} {i}u")
    lines += ["#endif /* NE_HOME_VOICE_INDICES_H */", ""]
    return "\n".join(lines)


def render() -> dict[str, str]:
    """Every file under main/gates/, as `neuroedge build` and this script produce it."""
    files: dict[str, str] = {}
    with tempfile.TemporaryDirectory() as out:
        build(AGENT / "agent.toml", target="esp32s3", board_id="esp32s3-box-3", out_dir=out)
        for gate in GATES:
            name = f"{gate}.netree.h"
            files[name] = (Path(out) / "gates" / name).read_text(encoding="utf-8")
    files["home_voice_indices.h"] = indices_header()
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="không ghi; thoát 1 nếu lệch")
    args = parser.parse_args()
    files = render()
    stale = [
        name
        for name, text in files.items()
        if not (TARGET / name).exists() or (TARGET / name).read_text(encoding="utf-8") != text
    ]
    extra = (
        sorted(p.name for p in TARGET.glob("*.h") if p.name not in files) if TARGET.exists() else []
    )
    if args.check:
        for name in stale + extra:
            print(f"lệch: targets/esp32s3/main/gates/{name}")
        return 1 if stale or extra else 0
    TARGET.mkdir(parents=True, exist_ok=True)
    for name, text in files.items():
        (TARGET / name).write_text(text, encoding="utf-8")
    for name in extra:
        (TARGET / name).unlink()
    print(f"đã ghi {len(files)} tệp vào targets/esp32s3/main/gates/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
