/* Generated by scripts/gen_firmware_vectors.py from fixtures/traces/ — do not edit. */
/* The canonical traces as the device replays them (TSK-S4-09): the recorded inputs; */
/* the verdicts, tokens and whether a pin is driven are the device's own. */
#ifndef NE_CANONICAL_VECTORS_H
#define NE_CANONICAL_VECTORS_H
#include "trace_vectors.h"
#include "vectors/unlock_door.netree.h"

/* happy-path.json #1: unlock_door@1.2.0 */
static const ne_fact ne_v_happy_path_0_facts[3] = {{1u, 1u, 1u, 0u, 0.0}, {1u, 1u, 0u, 0u, 0.0}, {1u, 1u, 1u, 0u, 0.0}};
static const char *const ne_v_happy_path_0_sources[3] = {"trace", "trace", "trace"};
static const ne_vector_command ne_v_happy_path_0_commands[1] = {{"door_lock", 0u, "pulse", 30000u}};
static const ne_vector_step ne_v_happy_path_steps[1] = {
    {0u, 0u, 0u, ne_v_happy_path_0_facts, ne_v_happy_path_0_sources, 0x1u, ne_v_happy_path_0_commands, 1u},
};
/* network_offline.json #1: unlock_door@1.2.0 */
static const ne_fact ne_v_network_offline_0_facts[3] = {{0u, 0u, 0u, 0u, 0.0}, {0u, 0u, 0u, 0u, 0.0}, {0u, 0u, 0u, 0u, 0.0}};
static const char *const ne_v_network_offline_0_sources[3] = {NULL, NULL, NULL};
static const ne_vector_command ne_v_network_offline_0_commands[1] = {{"door_lock", 0u, "pulse", 30000u}};
static const ne_vector_step ne_v_network_offline_steps[1] = {
    {0u, 1u, 0u, ne_v_network_offline_0_facts, ne_v_network_offline_0_sources, 0x1u, ne_v_network_offline_0_commands, 1u},
};
/* unverified_attempt.json #1: unlock_door@1.2.0 */
static const ne_fact ne_v_unverified_attempt_0_facts[3] = {{1u, 1u, 0u, 0u, 0.0}, {1u, 1u, 2u, 0u, 0.0}, {1u, 1u, 0u, 0u, 0.0}};
static const char *const ne_v_unverified_attempt_0_sources[3] = {"trace", "trace", "trace"};
static const ne_vector_command ne_v_unverified_attempt_0_commands[1] = {{"door_lock", 0u, "pulse", 30000u}};
static const ne_vector_step ne_v_unverified_attempt_steps[1] = {
    {0u, 0u, 0u, ne_v_unverified_attempt_0_facts, ne_v_unverified_attempt_0_sources, 0x1u, ne_v_unverified_attempt_0_commands, 1u},
};

#define NE_VECTOR_GATES 1u
static const ne_vector_gate ne_vector_gates[NE_VECTOR_GATES] = {
    {"unlock_door@1.2.0", ne_tree_unlock_door, (uint32_t)sizeof ne_tree_unlock_door, {"human_receptionist", "Y\303\252u c\341\272\247u c\341\272\247n \304\221\306\260\341\273\243c nh\303\242n vi\303\252n l\341\273\205 t\303\242n x\303\241c nh\341\272\255n tr\341\273\261c ti\341\272\277p tr\306\260\341\273\233c khi m\341\273\237 kh\303\263a.", NULL}}, /* sha256:2c20dc42616dbf9a3bf16b7967c3b01faa579e1186f55b928a85070a318a9ab5 */
};
#define NE_VECTORS 3u
static const ne_vector ne_vectors[NE_VECTORS] = {
    {"happy-path.json", "sha256:1b865281ee4c2cd75865f87df0d451e826c0f05a866cd704cbcfc68d272b14af", "villa-concierge@0.1.0", ne_v_happy_path_steps, 1u},
    {"network_offline.json", "sha256:dbb371ed7b9c9767979f20866d5da21deaf7fc45cb459d0edad69b9ccc874489", "villa-concierge@0.1.0", ne_v_network_offline_steps, 1u},
    {"unverified_attempt.json", "sha256:1e89d755bd1d8387c84406005d5819fdedd1c384ef6147ef4a19ea9375001ed3", "villa-concierge@0.1.0", ne_v_unverified_attempt_steps, 1u},
};
#endif /* NE_CANONICAL_VECTORS_H */
